### ISSUE TITLE
Error while running Streamlit command toml.decoder.TomlDecodeError: Empty value is invalid (line 3 column 1 char 25)

### ISSUE THREAD

**Issue by santos-k** [santos-k/WhatsApp-Chat-Analysis#1]
Getting toml error while running `streamlit` or `streamlit run app.py` in my local system.
Error message as below:
```
Traceback (most recent call last):
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\toml\decoder.py", line 812, in load_value
    raise ValueError("Empty value is invalid")
ValueError: Empty value is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\withu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\withu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Data Science\Projects\WhatsappChat-Analysis\venv\Scripts\streamlit.exe\__main__.py", line 7, in <module>
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\click\core.py", line 1657, in invoke
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\streamlit\web\cli.py", line 174, in main_run
    bootstrap.load_config_options(flag_options=kwargs)
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\streamlit\web\bootstrap.py", line 315, in load_config_options
    config.get_config_options(force_reparse=True, options_from_flags=options_from_flags)
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\streamlit\config.py", line 1093, in get_config_options
    _update_config_with_toml(file_contents, filename)
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\streamlit\config.py", line 971, in _update_config_with_toml
    parsed_config_file = toml.loads(raw_toml)
  File "d:\data science\projects\whatsappchat-analysis\venv\lib\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Empty value is invalid (line 3 column 1 char 25)

```

**Comment by santos-k** [comment]
To resolve this error need to delete `config.toml` file from the streamlit package directory
File path: `C:\Users\<username>\.streamlit\config.toml` just delete this file

**Comment by santos-k** [comment]
To resolve this error need to delete `config.toml` file from the streamlit package directory
File path: `C:\Users\withu\.streamlit\config.toml` just delete this file
